### ISSUE TITLE
Api error 503, Service temporarily unavailable

### ISSUE THREAD

**Issue by MARZOOQUE** [decentralised-dataexchange/bb-consent-api#475]
![image](https://github.com/decentralised-dataexchange/bb-consent-api/assets/61059336/9d7348d2-875d-46b7-a7b0-5a44715a9ad3)

**Comment by georgepadayatti** [comment]
@albinpa Why are we getting this error if password of organisation admin is changed ?

```
2023/11/07 09:44:01 Failed to get admin token:admin@retail.com with error: {invalid_grant Invalid user credentials}
panic: failed to get token

goroutine 1 [running]:
github.com/bb-consent/api/internal/user.GetOrganisationAdminToken({{0xc000450920?, 0x0?}, {0xc000450930?, 0x0?}}, {{0xc000510000, 0x28}, {0xc000450950, 0x10}, {0xc000450960, 0xe}, ...})
	/go/github.com/bb-consent/api/internal/user/users.go:790 +0x1c9
github.com/bb-consent/api/internal/tenant.SingleTenantConfiguration(0xc0003a8d80)
	/go/github.com/bb-consent/api/internal/tenant/single.go:234 +0x1cd
github.com/bb-consent/api/internal/cmd.StartApiCmdHandler(0xc0002df500?, {0xbf7a03?, 0x2?, 0x2?})
	/go/github.com/bb-consent/api/internal/cmd/start_api.go:93 +0x67f
github.com/spf13/cobra.(*Command).execute(0xc0002df500, {0xc000375080, 0x2, 0x2})
	/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:944 +0x847
github.com/spf13/cobra.(*Command).ExecuteC(0xc0002df200)
	/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:1068 +0x3bc
github.com/spf13/cobra.(*Command).Execute(...)
	/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:992
main.main()
	/go/github.com/bb-consent/api/main.go:29 +0xff
```

**Comment by georgepadayatti** [comment]
Then what is the point of having reset password endpoint ?
![2023-11-07_15-17](https://github.com/decentralised-dataexchange/bb-consent-api/assets/16397960/e475e607-4fac-44ad-8678-a94673a9efed)
